### ISSUE TITLE
点赞

### ISSUE THREAD

**Issue by yssource** [JaysonAlbert/rq-data#1]
.

**Comment by JaysonAlbert** [comment]
可以的，我原本只是本着自己用的想法放在这里，可以方便大家的话也是不错的。

**Comment by JaysonAlbert** [comment]
我找时间写个详细点的README

**Comment by yssource** [comment]
神奇. 
你本地是怎么拿到 下面这两个方法的呢?
[all_instruments](https://github.com/JaysonAlbert/rq-data/blob/master/scripts/rq.py#L15)
[get_price](https://github.com/JaysonAlbert/rq-data/blob/master/scripts/rq.py#L25)
所以好奇 这个 zipline-1m.ipynb 具体内容

**Comment by yssource** [comment]
我的初衷也是想本地完全运行 [rqalpha](https://github.com/ricequant/rqalpha), 自己尝试写一些 mod 扩展.
但是由于 他们 扩展 api 和 财务数据 不开放. 现在看到你这个项目, 觉着 是一种新的思路, 解决我的困惑

**Comment by JaysonAlbert** [comment]
@yssource readme已经更新

**Comment by JaysonAlbert** [comment]
@yssource 你可以看看我这个项目啊，回测实盘模拟盘都有https://github.com/JaysonAlbert/zipline

**Comment by yssource** [comment]
谢谢, 
1. 解惑了. 受益非线
2. 在学习你的 zipline ...

遇到一点 ngrok 小问题
我在 本地测试 
- localhost 没有问题, 能够 hello 出来结果
```
server.py  host = 'localhost' port = 1111
client.py   host = 'localhost' port = 1111
```
- xxx.free.ngrok.cc , 国内找了一家ngrok, 配置成 http 和 port: 80, 能够外网访问 本地 port:80 web 服务器. (说明ngrok成功启动,配置没有问题的).  然后将 ngrok 再改成 port:1111 进行本地socket测试, 但是 client 就是连不上本地 server. `connectting to server failed` , 或者一直都塞状态.
```
server.py  host = 'localhost' port = 1111
client.py   host = 'xxx.free.ngrok.cc' port = 1111
```

**Comment by JaysonAlbert** [comment]
@yssource 又加了几个文件
